name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Should build?
        id: should_build
        shell: bash
        run: |
          source utils.sh
          toml_prep "$(cat config.toml)"

          is_youtube_latest() {
            v=$(toml_get "YouTube" "version") || version=""
            if [ "$v" = latest ]; then
              declare -r cur_yt=$(sed -n 's/.*YouTube: \(.*\)/\1/p' build.md | xargs)
              [ -z "$cur_yt" ] && return 1 # empty, fail=>dont build
              declare -r last_ver=$(get_apk_vers "https://www.apkmirror.com/uploads/?appcategory=youtube" | get_largest_ver)

              echo "Current YT version: $cur_yt"
              echo "Latest YT version: $last_ver"
              [ "$cur_yt" != "$last_ver" ] # test success=>build, fail=>dont build
            else
              return 1 # Not experimental, dont build
            fi
          }

          is_patches_latest() {
            declare -r last_patches_url=$(wget -nv -O- https://api.github.com/repos/inotia00/revanced-patches/releases/latest | json_get 'browser_download_url' | grep 'jar')
            declare -r last_patches=${last_patches_url##*/}
            cur_patches=$(sed -n 's/.*Patches: \(.*\)/\1/p' build.md | xargs)

            echo "Current patches version: $cur_patches"
            echo "Latest patches version: $last_patches"
            [ "$cur_patches" != "$last_patches" ] # test success=>build, fail=>dont build
          }

          if ! git checkout update; then
            echo "First time building!"
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
          elif is_patches_latest || is_youtube_latest; then
            echo "Build!"
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
          else
            echo "Dont build!"
            echo "SHOULD_BUILD=0" >> $GITHUB_OUTPUT
          fi

    outputs:
      SHOULD_BUILD: ${{ steps.should_build.outputs.SHOULD_BUILD }}

  build:
    needs: check
    uses: ./.github/workflows/build.yml
    if: ${{ needs.check.outputs.SHOULD_BUILD == 1 }}
